Add random forest option for partial dependence
NCAR/echo-opt pull request #13
Opened 2023-06-22 20:04 UTC by katiedagon

Following our discussion on the MILES slack about the behavior of XGBoost sometimes generating negative values in partial dependence plots, I've attempted to update the code to add a random forest option. I set it up to use RF as the default, but that could be changed. I tested this with an existing echo run, and the PD plots are comparable to those produced with XGB, but still generating negative values which I'm not sure makes sense for these metrics. [Here](https://docs.google.com/presentation/d/1noQLFlN6g9eFbbdV-n0sL5LhApoFrZ7ExXFW5dPJB5U/edit?usp=sharing) are some example comparisons using a set of metrics from @mariajmolina - noting the vcorr_cust metric is likely out of date, but the valid_mae and vmse_extreme_outp should be relevant (and I believe should not have negative values).

I welcome comments/suggestions on any of the above, plus how best to let users choose between the two options, in addition to general comments about how the RF model is configured (e.g., hyperparameters).

2023-06-22 21:31 UTC, djgagne requested changes
@katiedagon Thank you for adding the random forest functionality. I added a couple of small suggestions that should address the remaining issues with negative output scores.

2023-06-22 21:31 UTC, djgagne commented on echo/src/partial_dependence.py
>      y_valid = yscaler.transform(np.expand_dims(y_valid, -1))
I would remove the yscaler since random forest and XG Boost do not need their input or output scaled to work well.

2023-06-22 21:31 UTC, djgagne commented on echo/src/partial_dependence.py
>      objective = "reg:squarederror"
Instead of hard coding the model hyperparameters, I would put them in a dictionary called hparams and make that a keyword argument for partial_dep.

2023-06-22 22:26 UTC, katiedagon commented on echo/src/partial_dependence.py
>      y_valid = yscaler.transform(np.expand_dims(y_valid, -1))
Ok, I will comment out yscaler lines similar to xscaler.

2023-06-22 22:28 UTC, katiedagon commented on echo/src/partial_dependence.py
>      objective = "reg:squarederror"
Sounds good - where should I define hparams?

2023-06-22 23:05 UTC, katiedagon commented on echo/src/partial_dependence.py
>      y_valid = yscaler.transform(np.expand_dims(y_valid, -1))
Hmmm...commenting out the yscaler lines did not address the negative output scores. I wonder if there is some additional scaling happening in the `partial_dependence_plot` function?

2023-06-23 15:20 UTC, katiedagon commented on echo/src/partial_dependence.py
>      y_valid = yscaler.transform(np.expand_dims(y_valid, -1))
Oops never mind, checking the wrong file. It worked!

2023-07-03 23:58 UTC, djgagne approved these changes
Changes look good to me. Merging.

2023-07-03 23:58 UTC, merged