Last minor update before new version
NCAR/echo-opt pull request #3
Opened 2022-02-07 21:56 UTC by jsschreck

A few smaller updates incorporated include addition of pruning options, a few configuration checks, and removal of unnecessary "hyper_opt" result files. Test for whether a supplied configuration contains the minimally required fields is forthcoming -- I may not include that to this pull request and wait until the larger update that will follow this merge due to configuration changes that will ensue to make ECHO easier to use.

2022-02-22 22:02 UTC, djgagne requested changes
I don't see any major code issues, but I would like to suggest using the entry-points functionality in setuptools and setup.py to make the scripts in echo runnable from the command line. See [here](https://python-packaging.readthedocs.io/en/latest/command-line-scripts.html) for more details about adding entry-points.

2022-02-22 22:48 UTC, charlie-becker approved these changes

2022-03-07 21:27 UTC, djgagne approved these changes

2022-03-07 21:27 UTC, djgagne commented
The changes look good to me. Go ahead and merge.

2022-03-08 15:35 UTC, merged